version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lms-net

  web:
    build: ./lms
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./lms:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - lms-net

volumes:
  postgres_data:

networks:
  lms-net:

